[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "shipping-logistics-api"
version = "1.0.0"
description = "An API for managing a logistics company that ships general goods via vessels."
authors = [
    { name="Dan Esteve", email="dan.lannes@outlook.com" }
    ]
requires-python = ">=3.13"
dependencies = [
    "pydantic",
    "uvicorn[standard]",
    "fastapi",
    "sqlalchemy",
    "alembic",
    "httpx"
    ]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8-pyproject",
    "mypy"
    ]

[tool.black]
line-length = 88
target-version = ["py313"]
extend-exclude = "(\\alembic|)"

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503"]
extend-exclude = [".venv", "alembic"]

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
disallow_untyped_defs = true
exclude = "^tests/"